config/routes.rb
Tasklist1::Application.routes.draw do
  resources :tasks

  resources :tasklists

  root :to => 'tasklists#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :done, :tasklist_id, :title
end

app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
  attr_accessible :title, :tasks_attributes

  has_many :tasks

  accepts_nested_attributes_for :tasks, :allow_destroy => true,
    :reject_if => lambda { |attributes| attributes[:title].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  # GET /tasklists
  # GET /tasklists.json
  def index
    @tasklists = Tasklist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasklists }
    end
  end

  # GET /tasklists/1
  # GET /tasklists/1.json
  def show
    @tasklist = Tasklist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tasklist }
    end
  end

  # GET /tasklists/new
  # GET /tasklists/new.json
  def new
    @tasklist = Tasklist.new
    4.times { @tasklist.tasks.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tasklist }
    end
  end

  # GET /tasklists/1/edit
  def edit
    @tasklist = Tasklist.find(params[:id])
    4.times { @tasklist.tasks.build }
  end

  # POST /tasklists
  # POST /tasklists.json
  def create
    @tasklist = Tasklist.new(params[:tasklist])

    respond_to do |format|
      if @tasklist.save
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully created.' }
        format.json { render json: @tasklist, status: :created, location: @tasklist }
      else
        format.html { render action: "new" }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasklists/1
  # PUT /tasklists/1.json
  def update
    @tasklist = Tasklist.find(params[:id])

    respond_to do |format|
      if @tasklist.update_attributes(params[:tasklist])
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasklists/1
  # DELETE /tasklists/1.json
  def destroy
    @tasklist = Tasklist.find(params[:id])
    @tasklist.destroy

    respond_to do |format|
      format.html { redirect_to tasklists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Home", root_path, :class => 'brand'
%ul.nav
  %li
    = link_to('Tasklists', tasklists_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tasklist1
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        %div.container
          = render 'layouts/navigation'
    %div#main{:role => "main"}
      %div.container
        %div.content
          %div.row
            %div.span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/tasklists/_form.html.haml
= form_for @tasklist do |f|
  %fieldset
    %legend
      = controller_name.singularize.capitalize

    - if @tasklist.errors.any?
      #error_explanation
        %h2= "#{pluralize(@tasklist.errors.count, "error")} prohibited this tasklist from being saved:"
        %ul
          - @tasklist.errors.full_messages.each do |msg|
            %li= msg

    = f.label :title
    = f.text_field :title
  %fieldset
    %legend
      = Tasks

    = f.fields_for :tasks do |t|
      %div
        = t.label :title
        = t.text_field :title
        = t.label :done do
          = t.check_box :done
          Done
        = t.label :_destroy do
          = t.check_box :_destroy
          Delete

  %div.form-actions
    = f.submit 'Save', :class => "btn btn-small"

app/views/tasklists/edit.html.haml
%h1 Editing tasklist

= render 'form'

= link_to 'Show', @tasklist, :class => "btn btn-small"
= link_to 'Back', tasklists_path, :class => "btn btn-small"

app/views/tasklists/index.html.haml
%h1 Listing tasklists

%table.table
  %tr
    %th Title
    %th
    %th
    %th

  - @tasklists.each do |tasklist|
    %tr
      %td= tasklist.title
      %td= link_to 'Show', tasklist, :class => "btn btn-small"
      %td= link_to 'Edit', edit_tasklist_path(tasklist), :class => "btn btn-small"
      %td= link_to 'Destroy', tasklist, :method => :delete, :data => { :confirm => 'Are you sure?' },
        :class => "btn btn-small btn-danger"

%br

= link_to 'New Tasklist', new_tasklist_path, :class => "btn btn-small"

app/views/tasklists/new.html.haml
%h1 New tasklist

= render 'form'

= link_to 'Back', tasklists_path

app/views/tasklists/show.html.haml
%h1 Tasklist
%h2
  Title:
  = @tasklist.title
%h3 Tasks:
%p
  %ul
    - @tasklist.tasks.each do |task|
      %li
        = task.title

= link_to 'Edit', edit_tasklist_path(@tasklist), :class => "btn btn-small"
= link_to 'Back', tasklists_path, :class => "btn btn-small"

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :done
    = f.check_box :done
  .field
    = f.label :tasklist_id
    = f.number_field :tasklist_id
  .actions
    = f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %tr
    %th Title
    %th Done
    %th Tasklist
    %th
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.title
      %td= task.done
      %td= task.tasklist_id
      %td= link_to 'Show', task
      %td= link_to 'Edit', edit_task_path(task)
      %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p
  %b Title:
  = @task.title
%p
  %b Done:
  = @task.done
%p
  %b Tasklist:
  = @task.tasklist_id

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path